/* Catchin' Up · Playbook tab: copy-paste replies, phone script, captions. Loaded by manage.html. Edit the text here; keep the structure. */
const PLAYBOOK = {
  intro: "Same voice everywhere: warm, short, one link, one next step. Change the name, paste, send. Taglish is fine when the customer writes Taglish. Every reply carries the one link: catchinup.tablebondgroup.ph",
  sections: [
    { title: "Messenger · Instagram · WhatsApp · Viber", items: [
      { q: "\"May table pa ba / can we reserve a table?\" (up to 6)", a: "Hi [Name]! Yes, you can book your table in under a minute here: catchinup.tablebondgroup.ph. Pick the branch, date and time and it shows you what's open. It's free, no deposit. See you at Catchin' Up!" },
      { q: "\"We're 10 pax / barkada birthday\" (7 to 18)", a: "Hi [Name]! For 7 to 18 guests, book under \"Big group\" here: catchinup.tablebondgroup.ph. It's ₱400 per head minimum consumable (food and drinks), and a ₱100 per head down payment holds your tables; the down payment is deducted from your bill. You can even order your food ahead so it's ready when you arrive. The site shows the QR for the down payment at the end. Just send us the screenshot with your reference number and you're confirmed!" },
      { q: "\"How much for 40 pax / company party?\" (20 and up)", a: "Hi [Name]! Exciting! The fastest way to see packages and get an estimate is here: catchinup.tablebondgroup.ph, tap \"Private event\". Choose your date, number of guests and packages, and it sends us your inquiry with a reference number. Our events team will then confirm the date and your final quote. If you'd rather, tell me the date and headcount and I'll walk you through it." },
      { q: "Down payment screenshot received", a: "Got it, thank you [Name]! Reference [BG-xxxxxx-xxx] is now confirmed for [date, time, branch, pax]. Please arrive within 15 minutes of your time; the tables are yours for 2 hours but stay as long as you like. See you!", note: "Then in the portal: open the booking → Down payment received." },
      { q: "Friday table request (up to 6)", a: "Hi [Name]! Fridays are walk-in only for small tables, so no reservation needed; just come early for the best spots. If you're 7 or more, you can still reserve a Friday as a big group here: catchinup.tablebondgroup.ph." },
      { q: "Big group request between Oct 20 and Dec 20", a: "Hi [Name]! From Oct 20 to Dec 20 we're on private-events season, so big-group bookings are paused. You can still book a free table for up to 6, or if you'd like the place to yourselves, I can set you up as a private event. Which works for you?" },
      { q: "\"The site didn't work\"", a: "Sorry about that [Name]! Can you tell me what it said on the screen (or send a screenshot)? Meanwhile, give me your branch, date, time and number of guests and I'll book it for you from here.", note: "Then in the portal: Bookings → Add by hand." },
      { q: "\"I didn't get an email\"", a: "No worries [Name], your reference is [TR-xxxxxx-xxx]; just show it at the door. See you!", note: "Find them under Bookings by name or mobile." },
      { q: "\"I'm 25 pax but it says private event\"", a: "Yes [Name], from 20 guests up it's a private event: you get the place (or the indoor area) to yourselves, and the minimum is on food and drinks you'd order anyway. Tap \"Private event\" here and pick your date: catchinup.tablebondgroup.ph" }
    ]},
    { title: "Phone · 30 seconds", items: [
      { q: "Opening", a: "Catchin' Up Pub, good [afternoon], this is [Name]!" },
      { q: "Table, up to 6", a: "Sure! The quickest way is our booking page, catchinup dot tablebondgroup dot ph, it shows you the open times right now and it's free. Or I can do it for you now: which branch, what date and time, and how many of you?", note: "Book it under Bookings → Add by hand, then: \"You're set, your reference is TR-[…]. Show it at the door, come within 15 minutes of your time, and the table's yours for 2 hours, stay longer if you like.\"" },
      { q: "7 to 18", a: "For a group that size we do a ₱400 per head minimum on food and drinks, and a ₱100 per head down payment that comes off your bill. I'll text you the link so you can pick your tables and pay the down payment by QR; the moment we get your screenshot you're confirmed." },
      { q: "20 and up", a: "Perfect, that's a private event. May I get your name, the date, and how many guests? I'll send you the link where you can see the packages and build your estimate, and our events team will call you back with the final quote." },
      { q: "Friday, up to 6", a: "Fridays are walk-in only for small tables, so no need to book, just come early. For 7 or more I can still reserve." },
      { q: "Closing", a: "Your reference is [TR-/BG-/CU-…]. Please arrive within 15 minutes of your time. See you at Catchin' Up!", note: "Always read the reference back. Never quote package prices from memory; the site and the proposal PDF are the source." }
    ]},
    { title: "Announcing it", items: [
      { q: "Pinned post / Facebook", a: "Booking at Catchin' Up just got easier. 🍻\nReserve your table, lock in your barkada's big night, or plan your private event in under two minutes: catchinup.tablebondgroup.ph\nLive availability, no deposit for tables up to 6, and your reference number straight to your inbox.\nSan Antonio Place · Jupiter Street · Makati" },
      { q: "Instagram caption", a: "New: book your night at Catchin' Up online. Tap the link in bio, pick your branch and time, done. Tables up to 6 are free to book. 7 to 18? Reserve your corner and order ahead. 20 and up? The whole place can be yours.\n#CatchinUpPub #MakatiNights #BookNow" },
      { q: "Auto-reply / away message", a: "Thanks for messaging Catchin' Up! While you wait, you can book a table or plan an event right now at catchinup.tablebondgroup.ph. We'll reply shortly." },
      { q: "Stories, 3 frames", a: "1. \"May plans tonight?\" over the hero video · link sticker: Book a table\n2. \"Barkada night? 7 to 18 pax, ₱100/head holds your tables\" · link sticker\n3. \"Your event, your venue\" over the San Antonio room · link sticker: Plan a private event", note: "Put the link in the Facebook Website field, Instagram bio, TikTok bio and Google Business. Retire any \"DM to reserve\" wording." }
    ]},
    { title: "Staff registration (internal)", items: [
      { q: "Group-chat message to employees", a: "Hi team! 👋\n\nWe're moving to our own staff system, and the first step is simple: everyone registers once online.\n\n📋 Registration link: https://catchinup.tablebondgroup.ph/register.html\n\nTakes about 5 minutes on your phone. Have these ready:\n• Your mobile number and an email you actually use (this becomes your login later)\n• Home address and an emergency contact\n• SSS, PhilHealth, Pag-IBIG and TIN numbers (leave blank if you don't have one yet, HR will follow up)\n• One valid ID: take a clear photo of the front, flat, all text readable\n• A selfie for your profile: plain background, face clear, no cap or sunglasses\n\nPick your branch (San Antonio, Jupiter, or Funhan Mart Arnaiz) and your position, tick the privacy consent, and submit. You'll see a \"Thanks\" screen; that's it.\n\nWhat happens next: nothing yet on your side. HR reviews each registration, then you'll get an email when your staff-app access is ready. Please don't wait for that email to register.\n\nDeadline: please finish by [day, date]. One registration per person; if you make a mistake, message [HR contact] instead of registering again.\n\nQuestions? Reply here or message [HR contact]. Thanks, everyone!" }
    ]}
  ]
};
let pbTab = 0;
function playbook(){
  const S = PLAYBOOK.sections;
  $("#main").innerHTML = `<h1>Playbook</h1><p class="muted" style="max-width:70ch">${esc(PLAYBOOK.intro)}</p>
    <div class="tabs">${S.map((s, i) => `<button aria-pressed="${pbTab === i}" data-i="${i}">${esc(s.title)}</button>`).join("")}<a class="btn sm ghost" href="playbook.pdf" target="_blank" style="margin-left:auto">Download PDF</a></div>
    <div class="grid">${S[pbTab].items.map((it, k) => `<div class="card"><h3 style="margin-bottom:8px">${esc(it.q)}</h3><div style="white-space:pre-wrap;font-size:14.5px;line-height:1.5;background:var(--soft);border-radius:10px;padding:12px 14px" id="pb-${k}">${esc(it.a)}</div>${it.note ? `<p class="small muted" style="margin:8px 0 0">${esc(it.note)}</p>` : ""}<div class="actions" style="margin-bottom:0"><button class="btn sm primary" onclick="pbCopy(${k})">Copy</button></div></div>`).join("")}</div>`;
  document.querySelectorAll(".tabs button").forEach(b => b.onclick = () => { pbTab = +b.dataset.i; playbook(); });
}
function pbCopy(k){ const t = PLAYBOOK.sections[pbTab].items[k].a; (navigator.clipboard ? navigator.clipboard.writeText(t) : Promise.reject()).then(() => toast("Copied, paste it in the chat"), () => { const ta = document.createElement("textarea"); ta.value = t; document.body.appendChild(ta); ta.select(); document.execCommand("copy"); ta.remove(); toast("Copied"); }); }
